apiVersion: v1
kind: Service
metadata:
  name: xzcom-exporter
  labels:
    app: xzcom-exporter
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: xzcom-exporter
  sessionAffinity: None
  type: ClusterIP
